# config-management.yaml
apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
  namespace: config-management-system
spec:
  clusterName: onprem.k8s.local
  policyController:
    enabled: true         
  git:
    syncRepo: git@github.com:ypenn21/anthos-config-manage.git
    syncBranch: main
    secretType: ssh
    policyDir: "."
    syncWait: 2
