kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-readers
  annotations:
    configmanagement.gke.io/cluster-selector: select-location-local
subjects:
  - kind: User
    name: cheryl@anthos_labs.com
    apiGroup: rbac.authorization.k8s.io
  - kind: User
    name: jane@anthos_labs.com
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: namespace-reader
  apiGroup: rbac.authorization.k8s.io
