apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eastwest-ingress
spec:
  defaultBackend:
    service:
      name: istio-eastwestgateway
      port:
        number: 30809
  rules:
  - http:
      paths:
      - path: /eastwest
        pathType: Exact
        backend:
          service:
            name: istio-eastwestgateway
            port:
              number: 30809
